#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGEvent2
@end

@interface SWGEvent2 : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* entryFee;

@property(nonatomic) NSNumber* parentMainEventId;

@property(nonatomic) NSNumber* parentCategoryId;

@property(nonatomic) NSNumber* multipleTicketsPerUser;

@property(nonatomic) NSNumber* groupSize;

@property(nonatomic) NSNumber* registrable;

@property(nonatomic) NSNumber* startTime;

@property(nonatomic) NSNumber* isVotingEnabled;

@property(nonatomic) NSString* intrestType;

@property(nonatomic) NSNumber* isEventTicketTransferable;

@property(nonatomic) NSString* backdropUrl;

@property(nonatomic) NSNumber* currentInvolvement;

@property(nonatomic) NSNumber* isCurrentUserIAMINED;

@property(nonatomic) NSNumber* isCurrentUserHavingTicket;

@property(nonatomic) NSNumber* condensedHead;

@end
