#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse20014Items.h"


@protocol SWGInlineResponse20014
@end

@interface SWGInlineResponse20014 : SWGObject


@property(nonatomic) NSArray<SWGInlineResponse20014Items>* items;

@end
