#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGEventHead.h"
@protocol SWGEventHead;
@class SWGEventHead;



@protocol SWGInlineResponse20010
@end

@interface SWGInlineResponse20010 : SWGObject


@property(nonatomic) NSArray<SWGEventHead>* items;

@end
