#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGComment.h"
@protocol SWGComment;
@class SWGComment;



@protocol SWGInlineResponse2006
@end

@interface SWGInlineResponse2006 : SWGObject


@property(nonatomic) NSArray<SWGComment>* items;

@end
