#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse2001Items.h"


@protocol SWGInlineResponse2001
@end

@interface SWGInlineResponse2001 : SWGObject


@property(nonatomic) NSArray<SWGInlineResponse2001Items>* items;

@end
