#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGInlineResponse2001Items
@end

@interface SWGInlineResponse2001Items : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* offerType;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* positionInList;

@property(nonatomic) NSString* creativeUrl;

@property(nonatomic) NSString* callToActionText;

@property(nonatomic) NSString* redeemInstructions;

@property(nonatomic) NSString* coupounCode;

@property(nonatomic) NSString* callNumber;

@property(nonatomic) NSString* smsText;

@property(nonatomic) NSString* url;

@end
