#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGPRLocation.h"


@protocol SWGLocationContainer
@end

@interface SWGLocationContainer : SWGObject


@property(nonatomic) NSNumber* mainEventLat;

@property(nonatomic) NSNumber* mainEventLon;

@property(nonatomic) NSArray<SWGPRLocation>* prLocations;

@end
