#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGMainEventStats
@end

@interface SWGMainEventStats : SWGObject


@property(nonatomic) NSNumber* totalIamins;

@property(nonatomic) NSNumber* totalIminersSharingContact;

@property(nonatomic) NSNumber* totalTickets;

@end
