#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGMainEvent1.h"


@protocol SWGSortedMainEvents
@end

@interface SWGSortedMainEvents : SWGObject


@property(nonatomic) NSArray<SWGMainEvent1>* trendingEvents;

@property(nonatomic) NSArray<SWGMainEvent1>* collegeEvents;

@property(nonatomic) NSArray<SWGMainEvent1>* clubEvents;

@property(nonatomic) NSArray<SWGMainEvent1>* concertEvents;

@end
