#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGMainEvent.h"
@protocol SWGMainEvent;
@class SWGMainEvent;



@protocol SWGSortedMainEvents
@end

@interface SWGSortedMainEvents : SWGObject


@property(nonatomic) NSArray<SWGMainEvent>* trendingEvents;

@property(nonatomic) NSArray<SWGMainEvent>* collegeEvents;

@property(nonatomic) NSArray<SWGMainEvent>* clubEvents;

@property(nonatomic) NSArray<SWGMainEvent>* concertEvents;

@end
