#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGEvent.h"
#import "SWGMainEvent.h"
@protocol SWGEvent;
@class SWGEvent;
@protocol SWGMainEvent;
@class SWGMainEvent;



@protocol SWGUserRoles
@end

@interface SWGUserRoles : SWGObject


@property(nonatomic) NSArray<SWGMainEvent>* isManagerForMainEvents;

@property(nonatomic) NSArray<SWGMainEvent>* isPrForEvents;

@property(nonatomic) NSArray<SWGEvent>* isEventHeadForEvents;

@end
