#import <Foundation/Foundation.h>
#import "SWGEvent2.h"
#import "SWGIAMIN1.h"
#import "SWGInlineResponse20010.h"
#import "SWGInlineResponse20010Items.h"
#import "SWGInlineResponse20015.h"
#import "SWGInlineResponse2004Items.h"
#import "SWGInlineResponse2005.h"
#import "SWGInlineResponse2006.h"
#import "SWGInlineResponse2008.h"
#import "SWGApi.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGEventHeadApi: NSObject <SWGApi>

extern NSString* kSWGEventHeadApiErrorDomain;
extern NSInteger kSWGEventHeadApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a voting candidate
/// 
///
/// @param eventId 
/// @param name 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20010Items*
-(NSURLSessionTask*) ehAddVotingCandidateWithEventId: (NSNumber*) eventId
    name: (NSString*) name
    completionHandler: (void (^)(SWGInlineResponse20010Items* output, NSError* error)) handler;


/// send anouncement to everyone
/// 
///
/// @param eventId 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehAnnounceAllWithEventId: (NSNumber*) eventId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// send anouncement to iaminers
/// 
///
/// @param eventId 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehAnnounceIAMINersWithEventId: (NSNumber*) eventId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// send anouncement to tickey holders
/// 
///
/// @param eventId 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehAnnounceTicketHoldersWithEventId: (NSNumber*) eventId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// Disable Voting
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehDisableVotingWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(NSError* error)) handler;


/// Edit Event
/// 
///
/// @param event 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2004Items*
-(NSURLSessionTask*) ehEditEventWithEvent: (SWGEvent2*) event
    completionHandler: (void (^)(SWGInlineResponse2004Items* output, NSError* error)) handler;


/// Enable Voting
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehEnableVotingWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(NSError* error)) handler;


/// give Ticket to iaminer
/// 
///
/// @param iAMIN 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehFreeUpgradeIAMINERWithIAMIN: (SWGIAMIN1*) iAMIN
    completionHandler: (void (^)(NSError* error)) handler;


/// get Event
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2004Items*
-(NSURLSessionTask*) ehGetEventWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse2004Items* output, NSError* error)) handler;


/// get IAMINers
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005*
-(NSURLSessionTask*) ehGetIAMINersWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse2005* output, NSError* error)) handler;


/// get Event
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20015*
-(NSURLSessionTask*) ehGetStatsWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse20015* output, NSError* error)) handler;


/// get Ticket holders for this event
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2006*
-(NSURLSessionTask*) ehGetTicketHoldersWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse2006* output, NSError* error)) handler;


/// get Voting Candidates
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20010*
-(NSURLSessionTask*) ehGetVotingCandidatesWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse20010* output, NSError* error)) handler;


/// Remove a voting candidate
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehRemoveAllCandidatesAndResetVotingWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(NSError* error)) handler;


/// Remove a voting candidate
/// 
///
/// @param eventId 
/// @param candidateId 
/// 
///  code:200 message:"OK"
///
/// @return 
-(NSURLSessionTask*) ehRemoveVotingCandidateWithEventId: (NSNumber*) eventId
    candidateId: (NSNumber*) candidateId
    completionHandler: (void (^)(NSError* error)) handler;


/// get History
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2008*
-(NSURLSessionTask*) ehgetHistoryWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGInlineResponse2008* output, NSError* error)) handler;



@end
