#import <Foundation/Foundation.h>
#import "SWGCategory.h"
#import "SWGEvent.h"
#import "SWGEventHead.h"
#import "SWGInlineResponse2001.h"
#import "SWGInlineResponse20010.h"
#import "SWGInlineResponse2002.h"
#import "SWGInlineResponse2005.h"
#import "SWGInlineResponse2008.h"
#import "SWGInlineResponse2009.h"
#import "SWGMainEvent.h"
#import "SWGMainEventStats.h"
#import "SWGManager.h"
#import "SWGPRRepresentative.h"
#import "SWGApi.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGManagerApi: NSObject <SWGApi>

extern NSString* kSWGManagerApiErrorDomain;
extern NSInteger kSWGManagerApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add Event Head to Event
/// 
///
/// @param ehEmail 
/// @param eventID 
/// 
///  code:200 message:"OK"
///
/// @return SWGEventHead*
-(NSURLSessionTask*) managerAddEventHeadWithEhEmail: (NSString*) ehEmail
    eventID: (NSNumber*) eventID
    completionHandler: (void (^)(SWGEventHead* output, NSError* error)) handler;


/// Add Manager to Main Event
/// 
///
/// @param manageremail 
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGManager*
-(NSURLSessionTask*) managerAddManagerWithManageremail: (NSString*) manageremail
    mainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGManager* output, NSError* error)) handler;


/// Add PR Representative to Main Event
/// 
///
/// @param pRemail 
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGPRRepresentative*
-(NSURLSessionTask*) managerAddPRWithPRemail: (NSString*) pRemail
    mainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGPRRepresentative* output, NSError* error)) handler;


/// Send Announcements to everyone
/// 
///
/// @param mainEventID 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerAnnounceAllWithMainEventID: (NSNumber*) mainEventID
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// Send Announcements to iaminer's only
/// 
///
/// @param mainEventId 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerAnnounceIAMINersWithMainEventId: (NSNumber*) mainEventId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// Send Announcements to ticket holders only
/// 
///
/// @param mainEventId 
/// @param message 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerAnnounceTicketHoldersWithMainEventId: (NSNumber*) mainEventId
    message: (NSString*) message
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete Category only if empty
/// 
///
/// @param categoryID 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerDeleteCategoryWithCategoryID: (NSNumber*) categoryID
    completionHandler: (void (^)(NSError* error)) handler;


/// Edit & Add Event
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerDeleteEventWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete Event Head
/// 
///
/// @param eventID 
/// @param ehEmail 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerDeleteEventHeadWithEventID: (NSNumber*) eventID
    ehEmail: (NSString*) ehEmail
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete Manager
/// 
///
/// @param mainEventId 
/// @param managerEmail 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerDeleteManagerWithMainEventId: (NSNumber*) mainEventId
    managerEmail: (NSString*) managerEmail
    completionHandler: (void (^)(NSError* error)) handler;


/// Delete PR if Amount collected = 0
/// 
///
/// @param mainEventID 
/// @param prEmail 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerDeletePRWithMainEventID: (NSNumber*) mainEventID
    prEmail: (NSString*) prEmail
    completionHandler: (void (^)(NSError* error)) handler;


/// Edit & Add Event
/// 
///
/// @param category 
/// 
///  code:200 message:"OK"
///
/// @return SWGCategory*
-(NSURLSessionTask*) managerEditCategoryWithCategory: (SWGCategory*) category
    completionHandler: (void (^)(SWGCategory* output, NSError* error)) handler;


/// Edit & Add Event
/// 
///
/// @param event 
/// 
///  code:200 message:"OK"
///
/// @return SWGEvent*
-(NSURLSessionTask*) managerEditEventWithEvent: (SWGEvent*) event
    completionHandler: (void (^)(SWGEvent* output, NSError* error)) handler;


/// Edit Main Event
/// 
///
/// @param mainEvent 
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) managerEditMainListingWithMainEvent: (SWGMainEvent*) mainEvent
    completionHandler: (void (^)(NSError* error)) handler;


/// get a event by event id
/// 
///
/// @param eventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGEvent*
-(NSURLSessionTask*) managerGetEventWithEventId: (NSNumber*) eventId
    completionHandler: (void (^)(SWGEvent* output, NSError* error)) handler;


/// get a categories under a main event
/// 
///
/// @param mainEventID 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2001*
-(NSURLSessionTask*) managerGetEventCategoriesWithMainEventID: (NSNumber*) mainEventID
    completionHandler: (void (^)(SWGInlineResponse2001* output, NSError* error)) handler;


/// get a category by id
/// 
///
/// @param categoryID 
/// 
///  code:200 message:"OK"
///
/// @return SWGCategory*
-(NSURLSessionTask*) managerGetEventCategoryWithCategoryID: (NSNumber*) categoryID
    completionHandler: (void (^)(SWGCategory* output, NSError* error)) handler;


/// get Event Heads for Event
/// 
///
/// @param eventID 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20010*
-(NSURLSessionTask*) managerGetEventHeadsWithEventID: (NSNumber*) eventID
    completionHandler: (void (^)(SWGInlineResponse20010* output, NSError* error)) handler;


/// get a events under a category
/// 
///
/// @param categoryID 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2002*
-(NSURLSessionTask*) managerGetEventsWithCategoryID: (NSNumber*) categoryID
    completionHandler: (void (^)(SWGInlineResponse2002* output, NSError* error)) handler;


/// Get Main Event History
/// 
///
/// @param maineventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005*
-(NSURLSessionTask*) managerGetHistoryWithMaineventId: (NSNumber*) maineventId
    completionHandler: (void (^)(SWGInlineResponse2005* output, NSError* error)) handler;


/// get a single Main Event
/// 
///
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGMainEvent*
-(NSURLSessionTask*) managerGetMainListingWithMainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGMainEvent* output, NSError* error)) handler;


/// get Managers for main event
/// 
///
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2009*
-(NSURLSessionTask*) managerGetManagersWithMainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGInlineResponse2009* output, NSError* error)) handler;


/// get PRs for main event
/// 
///
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2008*
-(NSURLSessionTask*) managerGetPRSWithMainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGInlineResponse2008* output, NSError* error)) handler;


/// Delete Main Event Stats
/// 
///
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGMainEventStats*
-(NSURLSessionTask*) managerGetStatsWithMainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGMainEventStats* output, NSError* error)) handler;



@end
