#import <Foundation/Foundation.h>
#import "SWGInlineResponse20012Items.h"
#import "SWGInlineResponse20015.h"
#import "SWGInlineResponse2004.h"
#import "SWGInlineResponse2005.h"
#import "SWGInlineResponse2005Items.h"
#import "SWGInlineResponse2006Items.h"
#import "SWGInlineResponse2008.h"
#import "SWGInlineResponse2008Items.h"
#import "SWGApi.h"

/**
* IAMIN API
* API Backend for the IAMIN App
*
* OpenAPI spec version: 1.0.0
* Contact: sanket@blackcurrantapps.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGPRApi: NSObject <SWGApi>

extern NSString* kSWGPRApiErrorDomain;
extern NSInteger kSWGPRApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Check in User
/// 
///
/// @param email 
/// @param eventId 
/// @param quantity 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2008Items*
-(NSURLSessionTask*) prCheckInByEmailWithEmail: (NSString*) email
    eventId: (NSNumber*) eventId
    quantity: (NSNumber*) quantity
    completionHandler: (void (^)(SWGInlineResponse2008Items* output, NSError* error)) handler;


/// Check in User
/// 
///
/// @param ticketID 
/// @param quantity 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2008Items*
-(NSURLSessionTask*) prCheckInByTicketIdWithTicketID: (NSNumber*) ticketID
    quantity: (NSNumber*) quantity
    completionHandler: (void (^)(SWGInlineResponse2008Items* output, NSError* error)) handler;


/// get Events
/// 
///
/// @param mainEventID 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2004*
-(NSURLSessionTask*) prGetEventListWithMainEventID: (NSNumber*) mainEventID
    completionHandler: (void (^)(SWGInlineResponse2004* output, NSError* error)) handler;


/// get History
/// 
///
/// @param maineventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2008*
-(NSURLSessionTask*) prGetHistoryWithMaineventId: (NSNumber*) maineventId
    completionHandler: (void (^)(SWGInlineResponse2008* output, NSError* error)) handler;


/// get IAMIN
/// 
///
/// @param iaminId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005Items*
-(NSURLSessionTask*) prGetIAMINWithIaminId: (NSNumber*) iaminId
    completionHandler: (void (^)(SWGInlineResponse2005Items* output, NSError* error)) handler;


/// get IAMINers for the main event sharing contacts
/// 
///
/// @param mainEventid 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005*
-(NSURLSessionTask*) prGetIAMINersWithMainEventid: (NSNumber*) mainEventid
    completionHandler: (void (^)(SWGInlineResponse2005* output, NSError* error)) handler;


/// get IAMIN
/// 
///
/// @param email 
/// @param eventId 
/// @param cellNo 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2005Items*
-(NSURLSessionTask*) prGetIaminByEmailWithEmail: (NSString*) email
    eventId: (NSNumber*) eventId
    cellNo: (NSString*) cellNo
    completionHandler: (void (^)(SWGInlineResponse2005Items* output, NSError* error)) handler;


/// get Self Profile
/// 
///
/// @param mainEventid 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20012Items*
-(NSURLSessionTask*) prGetPRRepresentativeWithMainEventid: (NSNumber*) mainEventid
    completionHandler: (void (^)(SWGInlineResponse20012Items* output, NSError* error)) handler;


/// get Stats
/// 
///
/// @param mainEventId 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20015*
-(NSURLSessionTask*) prGetStatsWithMainEventId: (NSNumber*) mainEventId
    completionHandler: (void (^)(SWGInlineResponse20015* output, NSError* error)) handler;


/// get Ticket
/// 
///
/// @param ticketID 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2006Items*
-(NSURLSessionTask*) prGetTicketByIdWithTicketID: (NSNumber*) ticketID
    completionHandler: (void (^)(SWGInlineResponse2006Items* output, NSError* error)) handler;


/// give Ticket
/// 
///
/// @param email 
/// @param eventId 
/// @param quantity 
/// @param cellNo 
/// @param remark 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2006Items*
-(NSURLSessionTask*) prGiveTicketByEmailAndCellWithEmail: (NSString*) email
    eventId: (NSNumber*) eventId
    quantity: (NSNumber*) quantity
    cellNo: (NSString*) cellNo
    remark: (NSString*) remark
    completionHandler: (void (^)(SWGInlineResponse2006Items* output, NSError* error)) handler;


/// give Ticket
/// 
///
/// @param iaminId 
/// @param quantity 
/// @param remark 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse2006Items*
-(NSURLSessionTask*) prGiveTicketbyIaminIdWithIaminId: (NSNumber*) iaminId
    quantity: (NSNumber*) quantity
    remark: (NSString*) remark
    completionHandler: (void (^)(SWGInlineResponse2006Items* output, NSError* error)) handler;


/// update location shown on the map to buyers
/// 
///
/// @param lat 
/// @param lon 
/// 
///  code:200 message:"OK"
///
/// @return SWGInlineResponse20012Items*
-(NSURLSessionTask*) prUpdateLocationWithLat: (NSNumber*) lat
    lon: (NSNumber*) lon
    completionHandler: (void (^)(SWGInlineResponse20012Items* output, NSError* error)) handler;



@end
